### ISSUE TITLE
Build failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by jkomyno** [facebook/proxygen#120] opened 2016-09-28 15:12 UTC
Here's the error part of the build log:

g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-5/README.Bugs for instructions.
Makefile:1604: recipe for target 'futures/Future.lo' failed
make[2]: **\* [futures/Future.lo] Error 1
make[2]: **\* Waiting for unfinished jobs....
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++1y -g -O2 -MT io/IOBufQueue.lo -MD -MP -MF io/.deps/IOBufQueue.Tpo -c io/IOBufQueue.cpp -o io/IOBufQueue.o >/dev/null 2>&1
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++1y -g -O2 -MT io/IOBuf.lo -MD -MP -MF io/.deps/IOBuf.Tpo -c io/IOBuf.cpp -o io/IOBuf.o >/dev/null 2>&1
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++1y -g -O2 -MT io/RecordIO.lo -MD -MP -MF io/.deps/RecordIO.Tpo -c io/RecordIO.cpp -o io/RecordIO.o >/dev/null 2>&1
libtool: compile:  g++ -DHAVE_CONFIG_H -I./.. -pthread -I/usr/include -std=gnu++1y -g -O2 -MT futures/ThreadWheelTimekeeper.lo -MD -MP -MF futures/.deps/ThreadWheelTimekeeper.Tpo -c futures/ThreadWheelTimekeeper.cpp -o futures/ThreadWheelTimekeeper.o >/dev/null 2>&1
make[2]: Leaving directory '/home/workteam/temp/proxygen/proxygen/folly/folly'
Makefile:1687: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/workteam/temp/proxygen/proxygen/folly/folly'
Makefile:1032: recipe for target 'all' failed
make: **\* [all] Error 2

I've already _sudo apt-get update'd_ and also restarted the machine, but it doesn't seem to work at all. Any advice, please?

**Comment by lanxi** [comment] 2016-10-18 23:42
Hi @jkomyno sorry about the delay! We are not seeing this error with our dev setting but I am going to try repro this using a similar environment. It looks like a problem building folly with libtool. Have you tried posting in folly group? Meanwhile for us we are using Ubuntu 14.04, libtool-2.4.2 and gcc-4.8.2

**Comment by TW80000** [comment] 2016-10-27 16:48
I'm not a part of the Proxygen team, and I don't know if this is helpful, but I downloaded Ubuntu 16.04.1 LTS this week, installed it on a VM, cloned Proxygen from Github, installed it, and ran the EchoServer example without any problems. That indicates to me that your error isn't caused by Ubuntu or Proxygen. Hopefully that helps you narrow your search for an answer.

**Comment by afrind** [comment] 2016-12-07 18:35
I think this usually happens when you don't have enough memory.  How much RAM do you have?

**Comment by spartucus** [comment] 2016-12-24 08:17
Same problem occurs when my Ubuntu 16.04 's RAM is 2 GB, in fact, system uses some, just left 1.9 GB valid. When I change RAM from 2 GB to 4 GB, build succeed.

It seems like that the Doc makes this note for a reason. 

`You will need at least 2 GiB of memory to compile proxygen and its dependencies.`

**Comment by afrind** [comment] 2017-03-01 19:32
Issue is resolved with more RAM, and the README is updated

**Closed by afrind** 2017-03-01 19:32 UTC
