### ISSUE TITLE
What's the best way of ensuring winsocket init first above all

### ISSUE THREAD

**Issue by FatsharkGo** [facebook/proxygen#324] opened 2020-06-09 15:03 UTC
I'm trying to build&run unittests of proxygen on Windows, on the project `SessionTests` , it throws me an exception of winsocket error10093:
```Failed to resolve address for '127.0.0.1': application has not called wsastartup or wsastartup failed. (error=10093)```

The callstack shows that the exception was triggered by initializing the global variable `localAddr`  in TestUtils.cpp, in the meanwhile, I noticed that breakpoints on `folly::NetOps::WinSockInit` were not hitted. It's so clear that the global variable `proxygen::localAddr` in TestUtils.cpp is inititlized priorior to  folly::netops::winsockInit.

Copying folly::netops::winsockInit to TestUtils.cpp can eliminate the winsocket error10093, but it's definitely a BAD idea, I want to know what's the best way to init winsocket in this case.

Any idea or code snippet is appreciated, thanks!

**Comment by jbeshay** [comment] 2022-09-19 20:54
Responding to this a little bit too late but better late than never.

We do not yet officially support building proxygen on Windows. None of the existing build tools (getdeps.py) or (build.sh) work for proxygen on Windows. Therefore, I am not able to reproduce the issue. However, just by reading your description, an easy solution for this issue would be to avoid initializing the SocketAddress in TestUtils.cpp at all. The global variables can be the address string and port number, then the SocketAddress can be initialized in the test class after the necessary initialization if the test is running on Windows.

I am going to proceed to close the issue. If you are still interested in fixing it, please feel free to contribute your changes for enabling the Windows build and the fix for the tests, and I can review them.

**Closed by jbeshay** 2022-09-19 20:54 UTC
